### PR TITLE
Showing that master is broken for 1.13

### PR DESCRIPTION
**Pull request by alexander-alvarez**
Related to the zoom? @taras 

```
not ok 4 Chrome 55.0 - Acceptance | ember-scrollbar: resizable scrollbar
actual: >
     200
expected: >
      100
stack: >
          at http://localhost:7357/assets/tests.js:26:14
          at Class.andThen (http://localhost:7357/assets/vendor.js:52564:33)
          at http://localhost:7357/assets/vendor.js:53250:19
          at isolate (http://localhost:7357/assets/vendor.js:53451:13)
          at http://localhost:7357/assets/vendor.js:53435:14
          at tryCatch (http://localhost:7357/assets/vendor.js:66669:14)
    Log: |
```

### CODE REVIEW

**Comment by taras** [comment]
Yes, it looks like it's related to zoom.

**Comment by taras** [comment]
@alexander-alvarez you gotta upgrade to 3+. It's at [3.1.0](https://github.com/ember-cli/ember-cli-qunit/blob/master/package.json) now. Try that.

**Comment by alexander-alvarez** [comment]
no dice.

**Comment by offirgolan** [comment]
@taras @alexander-alvarez please close this PR as it was resolved in #38.

**Pull request closed without merging**
