### PR TITLE
Mouse Events on Window Instead of DOM

### PR DESCRIPTION
**Pull request by alexander-alvarez**
cc @offirgolan 
Closes https://github.com/alphasights/ember-scrollable/issues/59

>Adding event listeners to window object
Instead of document.body, this allows for the mousemove being tracked even
outside of browser window, similar to how native browsers work.
If you drag and move the mouse outside of the browser window,
the scrollbar should still scroll until you mouseup

@nem-jmalatin let me know if this behaves as you expect.

### CODE REVIEW

**Comment by offirgolan** [comment]
@alexander-alvarez is this good to merge? Changes look good to me.

**Comment by alexander-alvarez** [comment]
On my side yeah

**Comment by offirgolan** [comment]
🔔  @nem-jmalatin

**Comment by offirgolan** [comment]
@alexander-alvarez can you resolve these conflicts? I'll merge this and make a new release.

**Comment by alexander-alvarez** [comment]
@offirgolan g2g

**Pull request merged**
