### PR TITLE
calculate scrollbar width correctly

### LINKED ISSUE #64: Native and virtual scrollbar visible in Internet Explorer
```hbs
<div style="height: 50vh; width: 80%;">
  {{#ember-scrollable}}
    <div style="height: 300vh; background: linear-gradient(0deg, #009245, #FCEE21);">
    </div>
  {{/ember-scrollable}}
</div>
```

image

Tested in Internet Explorer 11 with Edge rendering engine on Windows 7. Also happens with the IE 10 and IE 9 rendering engine.

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #64

Scrollbar width is still calculated repeatedly; once for every component.

### CODE REVIEW

**Comment by buschtoens** [comment]
I don't have internet access on our Windows VM for testing IE, so I can't verify this, but my best guess is that the new jQuery version calculates `.width()` and `.innerWidth()` differently, as they both seem to exclude the scrollbar width. I changed the logic a bit and now it should work regardless of the version used.

**Comment by buschtoens** [comment]
I improved the logic even more. We now don't even need to sniff for Firefox.

**Comment by buschtoens** [comment]
The scrollbar thickness is now mesaured once in a service and cached from there on.

**Comment by offirgolan** [comment]
@buschtoens can you resolve conflicts and fix any failing test cases?

**Comment by buschtoens** [comment]
Yeppa. Did this as the last thing before going home. 😅 

I'll fix this as the first thing tomorrow. :)

**Comment by buschtoens** [comment]
@offirgolan Ready for your eyes. :eyes: 

I'm tempted to say that this one failing test actually isn't this PR's fault.

**Comment by buschtoens** [comment]
This is the only test failing and only for the `ember-release` scenario.

https://travis-ci.org/alphasights/ember-scrollable/jobs/214383533#L921-L931

```
not ok 31 Chrome 57.0 - Integration | Component | scroll content element: Horizontal: Initial offset triggers a scroll event
    ---
        expected: >
            Max depth.,Max depth.
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:532:14)
                at fn (http://localhost:7357/assets/vendor.js:11483:18)
                at invokeWithOnError (http://localhost:7357/assets/vendor.js:10914:16)
                at Queue.flush (http://localhost:7357/assets/vendor.js:10973:9)
                at DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:11097:15)
                at Backburner.end (http://localhost:7357/assets/vendor.js:11167:23)
```

I'll see if I can replicate this locally.

**Comment by buschtoens** [comment]
The test results appear to be pretty inconsistent. When I run `yarn test` the tests run in Chrome and randomly fail. :worried: 

The test in question is:
```
not ok 22 Chrome 57.0 - Integration | Component | ember scrollbar: Horizontal: onJumpTo first argument is true when click to the left of handle
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:329:14)
                at Backburner.join (http://localhost:7357/assets/vendor.js:20057:31)
                at Function.run$1.join (http://localhost:7357/assets/vendor.js:39007:28)
                at http://localhost:7357/assets/vendor.js:29015:37
                at flaggedInstrument (http://localhost:7357/assets/vendor.js:38434:14)
                at http://localhost:7357/assets/vendor.js:29014:48
        message: >
            towardsAnchor should be true if going towards anchor
        Log: |
    ...
```

Ironically, the test case that failed in Travis, never fails locally.

**Comment by buschtoens** [comment]
Running the tests manually in Chrome succeeds consistently. I guess this is some very unfortunate race condition.

image

**Comment by alexander-alvarez** [comment]
@buschtoens  do we need to update https://github.com/alphasights/ember-scrollable/blob/master/tests/integration/components/ember-scrollbar-test.js#L169 ?

**Comment by buschtoens** [comment]
> @buschtoens do we need to update https://github.com/alphasights/ember-scrollable/blob/master/tests/integration/components/ember-scrollbar-test.js#L169 ?

I don't think so. At least the current setup seems to work for Firefox, Chrome and surprisingly IE as well.

However...

Running tests manually in Firefox, it fails consistently for a different case. But it does so on `master` as well. So that's a different issue (#66).
```
Acceptance | ember-scrollbar: When element resized from no-overflow => overflow => no-overflow, no scrollbar is visible on mouseover (3, 4, 7)

> there is no overflow as 18 < 200px
  Expected: 18
  Result: 19

> there is overflow as 494 > 200px@ 1247 ms
  Expected: 494
  Result: 509

> failed
  Expected: 18
  Result: 19
```

Running tests in IE is a different nightmare: #77

**Comment by buschtoens** [comment]
After applying #68, there are no new failing test cases in IE compared to `master`, or #68 for that matter.

**Comment by buschtoens** [comment]
Rebased on the current `master`. All tests pass now (on Travis).

Before that I accidentally rebased onto my own `origin/master` instead of `upstream/master` and the tests still passed on Travis. So it was a random fail / race condition after all.

**Comment by alexander-alvarez** [comment]
*sigh... The struggles of web dev.

**Comment by offirgolan** [comment]
@buschtoens do we still need the `includePolyfill` option? I thought the last merged PR solved that issue.

**Comment by buschtoens** [comment]
@offirgolan of course you're​ correct. I forgot to remove the commit. 🙈

I'm currently commuting to work. I'll remove it, when I'm there. 😉

**Comment by buschtoens** [comment]
Commit removed and tests still pass. :white_check_mark: :grin:

**Comment by offirgolan** [comment]
@buschtoens awesome job! Thanks for seeing this through! 😄

**Pull request merged**
