### PR TITLE
remove all ::scrollbar pseudo selectors

### LINKED ISSUE #76: Wrong width calculation / overflowing child
image

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #76

### CODE REVIEW

**Comment by buschtoens** [comment]
Tested in Chrome and Firefox on Linux and IE 11 on Windows.

**Comment by alexander-alvarez** [comment]
cc @offirgolan (still don't have access tot his repo sad :panda_face: )

**Comment by offirgolan** [comment]
Sorry for the delay guys. Released this with `v0.4.7`. Thanks @buschtoens!

**Comment by marceloandrader** [comment]
Thanks @buschtoens

**Comment by TigranSimonyan** [comment]
## After commit I have two scrollbar  :(

screen shot 2017-07-26 at 21 15 49

**Comment by buschtoens** [comment]
@TigranSimonyan which browser (version as well), OS and version of ember-scrollable are you using? Can you please share your template and CSS?

**Comment by TigranSimonyan** [comment]
I am using macOS Sierra and testing chrome version 59.0.3071.115 (Official Build) (64-bit)
I can even reproduce this in your demo version https://alphasights.github.io/ember-scrollable/
and for vertical scroll change
```
.tse-scrollbar.vertical .drag-handle{
    right: 2px;
    width: 7px;
}
```
to
```
.tse-scrollbar.vertical .drag-handle{
    right: 10px;
    width: 7px;
    background:red;
}
```

now you can see browser default scroll and also your scroll handler.
Actually this is being reproduced in all browsers (firefox, safari)
Previously you had: 
```
.tse-scrollable .tse-scroll-content::-webkit-scrollbar {
    width: 0;
    height: 0; 
}
```
this was helping in case of chrome/safari case but in firefox it was same. In current version you have removed this.
In case if you will tell that why you do right:10px; :) I can tell 
1. we need the drag handler to be outside of the container by design
2. if we even don't move it you can see that black scrollbar is covering your drag handler
screen shot 2017-07-28 at 18 50 56
screen shot 2017-07-28 at 18 50 54


--------
I don't think in case of using browser overflow:scroll; there is no css to hide the browser handler, I understand that this is better for performance but we have this kind of issue in this case

**Comment by buschtoens** [comment]
Goddammit. I think I know what's up. macOS renders these iOS like scrollbars which just float over the content. Basically what we want to emulate.

I have some MacBooks at work which I can use to test. But that'll be after the weekend.

But to verify, if you open the Sytem Preferences, try setting scrollbars to always visible.

image

Just so I understand you correctly: Firefox also renders these floaty scrollbars on macOS?

**Pull request merged**
