### PR TITLE
build: include Babel polyfill

### PR DESCRIPTION
**Pull request by buschtoens**
Resolves IE freezing mentioned in #67

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
relates to https://github.com/alphasights/ember-scrollable/pull/51 no?

**Comment by buschtoens** [comment]
Not really. The `ember-cli-build.js` file only affects the build of the addon dummy app. 

We could force the polyfill inclusion via the `included` hook, but I consider that bad practice. We should probably add a note to the readme though.

**Comment by alexander-alvarez** [comment]
i'm pretty sure https://github.com/alphasights/ember-scrollable/issues/50 is the only non i.e. functionality in `ember-scrollable`, do you think there's something else that requires the pollyfills for compatibility?

**Comment by buschtoens** [comment]
I believe it's the only thing. In my case it doesn't really matter as we include the polyfill anyways, as we use other ES6 features in our app as well. The polyfill and regenerator runtime add about 28 k gzipped, possibly less.

I can understand that some folks would not want to add this (arguably small) added weight for an addon that could *easily* avoid this.

While I'd rather stay true to ES6 all the way, I have no objections against including the inline safety net (https://github.com/alphasights/ember-scrollable/issues/50#issuecomment-277863385) or a one line polyfill.

**Comment by buschtoens** [comment]
Superseded by #69.

**Pull request closed without merging**
